apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: default
  labels:
    app: eureka-server
spec:
  type: NodePort
  ports:
    - port: 8802
      nodePort: 8802 #service对外开放端口
  selector:
    app: eureka-server
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: eureka-server #名称
  labels:
    app: eureka-server #标注
spec:
  replicas: 1 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers: #docker容器的配置
        - name: eureka-server
          image: "ascdc/jdk8"  #使用的镜像
          imagePullPolicy: IfNotPresent #pull镜像时机，
          ports:
            - containerPort: 8802 #容器对外开放端口

          volumes:
            - ./eureka-server-0.0.1-SNAPSHOT.jar:/app.jar
            - ./auto-code:/script/